---
- name: Build, push and deploy container image from local Dockerfile
  hosts: localhost
  connection: local

  tasks:
    - name: Check if pytest is installed
      stat:
        path: ~/.local/bin/pytest
      register: stat_result

    - name: "If pytest couldn't be found, exit"
      fail:
        msg: "Please make sure ~/.local/bin/pytest is available"
      when: not stat_result.stat.exists

    # task will fail if container is not running, but it will continue with the execution.  
    - name: "Check if container is not running already"
      command: ~/.local/bin/pytest
      ignore_errors: yes
      no_log: true
      register: test_result
    - block:
        - name: "End playbook if container is already running"
          debug:
            msg: "Aborting, localhost:8080/sample is already serving"
        - meta: end_play
      when: test_result.stdout.find('failed') == -1

    - name: "Build the image"
      command: docker build -t webapp .

    - name: "Tag the image"
      command: docker tag webapp quay.io/nnosenzo/webapp:latest

    - name: "Push to quay registry to store it permanently"
      command: docker push quay.io/nnosenzo/webapp:latest

    - name: "Run container"
      command: docker run -d -p 8080:8080 quay.io/nnosenzo/webapp:latest

    #  Pause for some seconds until the container is up and running
    - pause: seconds=4

    - name: "Test image once running"
      command: ~/.local/bin/pytest
      register: testoutput
      
    - name: Print test results
      debug:
        msg: "Test Result: {{ testoutput.stdout }}"